// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'markdown-outline-empty'
  | 'markdown-outline-title'
  | 'markdown-outline-toggle'
  | 'menuitem-create-item-md'
  | 'menuitem-create-md'
  | 'menuitem-create-standalone-md'
  | 'menuitem-open-md'
  | 'pref-help'
  | 'pref-open-settings'
  | 'pref-title'
  | 'prefs-title'
  | 'sidebar-attachment-gone'
  | 'sidebar-empty'
  | 'sidebar-empty-no-item'
  | 'sidebar-new-md'
  | 'sidebar-open-in-tab'
  | 'sidebar-save-failed'
  | 'sidebar-saved'
  | 'sidebar-section-label'
  | 'sidebar-section-tooltip'
  | 'sidebar-switch-live'
  | 'sidebar-switch-source'
  | 'sidebar-switch-to-tab'
  | 'sidebar-trash'
  | 'sidebar-unsaved'
  | 'startup-begin'
  | 'startup-finish';
