// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-create-md'
  | 'menuitem-open-md'
  | 'pref-enable'
  | 'pref-font-size'
  | 'pref-frontmatter'
  | 'pref-help'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
