// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'markdown-outline-empty'
  | 'markdown-outline-title'
  | 'markdown-outline-toggle'
  | 'menuitem-create-item-md'
  | 'menuitem-create-md'
  | 'menuitem-create-standalone-md'
  | 'menuitem-open-md'
  | 'pref-enable'
  | 'pref-font-size'
  | 'pref-frontmatter'
  | 'pref-help'
  | 'pref-shortcut-standalone'
  | 'pref-shortcut-standalone-help'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
